#!/bin/bash

# wrapper for running src/count_annotations.js in a container

# override the working directory with an environment variable
: ${TYPEWEAVER_CA_WORKDIR:=/code}

# use podman by default
# override by calling script with `DOCKER=docker ./run.sh`
: ${DOCKER:=podman}

$DOCKER run --rm \
    --volume $(pwd)/../../data:/data:rw \
    --entrypoint node  \
    --workdir $TYPEWEAVER_CA_WORKDIR \
    typeweaver-weaver:ecoop2023-artifact count_annotations.js "$@"
