// Generated by LiveScript 1.6.0
(function(){
  var VERSION: string, parseType: Function, parsedTypeCheck: Function, typeCheck: Function;
  VERSION = '0.4.0';
  parseType = require('./parse-type');
  parsedTypeCheck = require('./check');
  typeCheck = function(type: string, input: Element, options: object){
    return parsedTypeCheck(parseType(type), input, options);
  };
  module.exports = {
    VERSION: VERSION,
    typeCheck: typeCheck,
    parsedTypeCheck: parsedTypeCheck,
    parseType: parseType
  };
}).call(this);
