[package]
name = "ts_infer_incoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_common = "0.29.5"
swc_ecma_parser = "0.122.7"
