// Generated by LiveScript 1.6.0
(function(){
  var VERSION: String, parseType: Function, parsedTypeCheck: Function, typeCheck: Function;
  VERSION = '0.4.0';
  parseType = require('./parse-type');
  parsedTypeCheck = require('./check');
  typeCheck = function(type: String, input: Element, options: Object){
    return parsedTypeCheck(parseType(type), input, options);
  };

  export default {
    VERSION: VERSION,
    typeCheck: typeCheck,
    parsedTypeCheck: parsedTypeCheck,
    parseType: parseType
  };
}).call(this);
