#!/usr/bin/env Rscript

suppressMessages(library(tidyverse))
suppressMessages(library(extrafont))
suppressMessages(loadfonts())

# The csv files use old names, e.g. SantaCoder instead of StarCoder
INPUT_SYSTEMS = list(
  tsc="tsc",
  DeepTyper="dt",
  LambdaNet="ln",
  InCoder="ic",
  SantaCoder="sc"
)

SYSTEMS = list(
  TypeScript="tsc",
  DeepTyper="dt",
  LambdaNet="ln",
  InCoder="ic",
  StarCoderBase="sc"
)

data_dir <- "../../data"
csv_dir <- paste0(data_dir, "/notes/csv")
figures_dir <- paste0(data_dir, "/notes/dissertation-figures")

if (!file.exists(figures_dir)) {
  dir.create(figures_dir)
}

################################################################################
# Initialize theme
################################################################################

theme_set(
  theme_bw() +
    theme(text = element_text(family="Palatino", size=12),
          panel.grid.major = element_line(color="gray", size=0.2),
          panel.grid.minor = element_line(color="gray", size=0.2, linetype="dotted"),
          axis.ticks = element_line(size=0.05),
          legend.margin = margin(0, 0, 0, 0),
          legend.position = "bottom",
          legend.key.size = unit(0.5, "cm"),
          legend.title = element_blank()))
brewer <- "Blues"

################################################################################
# Helper functions
################################################################################

# Read in summary CSVs with the names {prefix}.{system}.csv, and return a tibble
read_summary_csv <- function(prefix, ...) {
  tbls <- Map(function(s) {
    filename <- paste0(prefix, ".", s, ".csv")
    path <- paste0(csv_dir, "/", filename)
    if (file.exists(path)) {
      cat("Reading file:", path, "\n")
      tbl <- read_csv(path, show_col_types=FALSE, ...)
    }
  }, INPUT_SYSTEMS)
  bind_rows(tbls) %>% rename_system()
}

# constants.tex <- paste0(figures_dir, "/", "constants.tex")
# cat("% DO NOT MODIFY: this file is generated by an R script\n", file=constants.tex)
# save.constant.tex <- function(constant) {
#   output <- paste0("\\newcommand{\\", substitute(constant), "}{", constant, "}\n")
#   cat("Writing constant", substitute(constant), "=", constant, "to", constants.tex, "\n")
#   cat(output, file=constants.tex, append=TRUE)
# }

constants.txt <- paste0(figures_dir, "/", "constants.txt")
cat("% DO NOT MODIFY: this file is generated by an R script\n", file=constants.txt)
save.constant.txt <- function(constant) {
  output <- paste0(substitute(constant), " = ", constant, "\n")
  cat("Writing constant", substitute(constant), "=", constant, "to", constants.txt, "\n")
  cat(output, file=constants.txt, append=TRUE)
}

# Outputs a tibble in LaTeX format (minus the headers)
# Essentially just adds the & between columns and \\ at the end of each row
save.table <- function(table) {
  file <- paste0(figures_dir, "/", substitute(table))
  cat("Writing table:", file, "\n")
  cat("% DO NOT MODIFY: this file is generated by an R script\n", file=file)
  for (row in 1:nrow(table)) {
    for (col in 1:ncol(table)) {
      cat(table[[row, col]], file=file, append=TRUE)
      if (col < ncol(table)) cat(" & ", file=file, append=TRUE)
    }
    cat(" \\\\\n", file=file, append=TRUE)
  }
}

save.csv <- function(tbl) {
  file <- paste0(figures_dir, "/", substitute(tbl))
  write_csv(tbl, file)
}

save.graph <- function(plot, width=7.5, height=5) {
  file <- paste0(figures_dir, "/", substitute(plot))
  cat("Writing plot:", file, "\n")
  ggsave(file, plot=plot, width=width, height=height)
}

rename_datasets <- function(tbl) {
  tbl %>%
    mutate(Dataset=case_when(str_starts(Dataset, "top1k-typed-nodeps") ~ "DefinitelyTyped, no deps",
                             str_starts(Dataset, "top1k-typed-with-typed-deps") ~ "DefinitelyTyped, with deps",
                             str_starts(Dataset, "top1k-untyped-nodeps") ~ "Never typed, no deps",
                             str_starts(Dataset, "top1k-untyped-with-typed-deps") ~ "Never typed, with deps"))
}

rename_system <- function(tbl) {
  tbl %>%
    mutate(System=case_when(str_equal(System, "SantaCoder") ~ "StarCoderBase",
                            .default = System)) %>%
    mutate(System=case_when(str_equal(System, "tsc") ~ "TypeScript",
                            .default = System))
}

filter_es6_renamed <- function(tbl) {
  tbl %>% filter(str_ends(Dataset, "es6")) %>% rename_datasets()
}

filter_pre_es6_renamed <- function(tbl) {
  tbl %>% filter(!str_ends(Dataset, "es6")) %>% rename_datasets()
}

reorder_systems <- function(tbl) {
  tbl$System <- factor(tbl$System,
                       levels=names(SYSTEMS))
  arrange(tbl, factor(System, levels=names(SYSTEMS)))
}

pivot_data <- function(tbl) {
  tbl %>%
    pivot_wider(names_from=System, values_from=!c(System, Dataset),
                names_glue="{SYSTEMS[System]}.{.value}",
                names_vary="slowest")
}

format_numbers <- function(tbl) {
  tbl %>%
    mutate(across(where(is.double), scales::label_number(accuracy=0.1))) %>%
    mutate(across(where(is.integer), scales::label_comma()))
}

percent_bar_graph <- function(data, name.y) {
  data %>%
    ggplot(aes(x=System, y=Percent, fill=Dataset)) +
      geom_bar(stat="identity", position=position_dodge()) +
      theme(axis.title.x=element_blank()) +
      scale_y_continuous(limits=c(0, 100),
                         breaks=seq(0, 100, by=20),
                         labels=scales::label_percent(scale=1)) +
      guides(fill=guide_legend(nrow=2)) +
      scale_fill_brewer(palette=brewer, direction=-1)
}

################################################################################
# Table: package counts, file counts, and lines of code for each dataset
################################################################################

loc_per_file <- read_csv(paste0(csv_dir, "/", "file_loc.csv"), col_types="ccci") %>%
  filter_es6_renamed()

loc_per_package <- loc_per_file %>%
  group_by(Dataset, Package) %>%
  summarize(.groups="drop", `Lines of code`=sum(`Lines of code`))

dataset_summary <- loc_per_file %>%
  group_by(Dataset, Package) %>%
  summarize(.groups="drop_last", Files=n(), `Lines of code`=sum(`Lines of code`)) %>%
  summarize(Packages=n(), Files=sum(Files), `Lines of code`=sum(`Lines of code`))

totalpkgs <- dataset_summary %>% pull(Packages) %>% sum()
save.constant.txt(totalpkgs)

dataset_summary.tex <- dataset_summary %>%
  add_row(Dataset="Overall",
          Packages=sum(.$Packages),
          Files=sum(.$Files),
          `Lines of code`=sum(.$`Lines of code`)) %>%
  format_numbers()

save.table(dataset_summary.tex)

################################################################################
# Graph: distribution of package lines of code
################################################################################

package_loc_cdf.pdf <- loc_per_package %>%
  ggplot(aes(x=`Lines of code`)) +
  stat_ecdf() +
  scale_x_continuous(breaks=seq(0, 10000, by=2000), labels=scales::label_comma()) +
  scale_y_continuous(breaks=seq(0, 1, by=0.2), labels=scales::percent) +
  labs(y="Packages")

save.graph(package_loc_cdf.pdf, height=3.75)

################################################################################
# Table: number/percent of packages that type check
################################################################################

compute_typecheck_summary <- function(typecheck_data) {
  typecheck_summary <- typecheck_data %>%
    group_by(System, Dataset) %>%
    summarize(.groups="drop", `Type checks`=sum(`Type checks`), n=n(), Percent=`Type checks` / n * 100) %>%
    reorder_systems()

  typecheck_overall <- typecheck_summary %>%
    group_by(System) %>%
    summarize(`Type checks`=sum(`Type checks`), n=sum(n), Percent=`Type checks` / n * 100) %>%
    mutate(Dataset="Overall") %>%
    reorder_systems()

  typecheck_summary %>% bind_rows(typecheck_overall)
}

typecheck_data_full <- read_summary_csv("typecheck", col_types="ccci")

# ES6 datasets
typecheck_data <- typecheck_data_full %>%
  filter_es6_renamed()

typecheck_summary <- compute_typecheck_summary(typecheck_data)

typecheck_summary.tex <- typecheck_summary %>%
  rename(typechecks=`Type checks`, pct=Percent) %>%
  pivot_data() %>%
  format_numbers()

save.table(typecheck_summary.tex)

################################################################################
# Constants: min/max percent of packages that type check
################################################################################

typecheck_overall_pcts <- typecheck_summary %>%
  filter(Dataset == "Overall") %>%
  pull(Percent) %>%
  as.numeric() %>%
  round()

typecheckPkgMin <- min(typecheck_overall_pcts)
save.constant.txt(typecheckPkgMin)

typecheckPkgMax <- max(typecheck_overall_pcts)
save.constant.txt(typecheckPkgMax)

################################################################################
# Graph: percent of packages that type check
################################################################################

typecheck_summary.pdf <-
  percent_bar_graph(typecheck_summary) +
  labs(y="Packages")

save.graph(typecheck_summary.pdf)

################################################################################
# Table: number/percent of files with no errors
################################################################################

# tsc migration generates .d.ts files, not .ts files
# So rename .ts to .d.ts
fix_tsc_names <- function(tbl) {
  tbl %>%
    mutate(File=case_when(str_equal(System, "tsc") ~ str_replace(File, "\\.ts$", ".d.ts"),
                          str_equal(System, "TypeScript") ~ str_replace(File, "\\.ts$", ".d.ts"),
                          .default = File))
}

compute_errors_per_file <- function(error_data, typecheck_data) {
  # expand_grid gets every file for every system, then left_join gets the files
  # that we attempted to type check, and we full_join that with the error count
  # (since the error count doesn't include files with 0 errors)
  errors_per_file <- error_data %>%
    group_by(System, Dataset, Package, File) %>%
    summarize(.groups="drop", Errors=sum(Count)) %>%
    full_join(left_join(typecheck_data,
                        expand_grid(System=names(SYSTEMS), loc_per_file),
                        by=c("System", "Dataset", "Package")),
              by=c("System", "Dataset", "Package", "File")) %>%
    replace_na(list(Errors=0)) %>%
    select(!(`Lines of code`:`Type checks`)) %>%
    arrange(System, Dataset, Package, File) %>%
    reorder_systems() %>%
    fix_tsc_names()
}

compute_errorfree_files_summary <- function(errors_per_file) {
  errorfree_files_summary <- errors_per_file %>%
    group_by(System, Dataset) %>%
    summarize(.groups="drop", `No errors`=sum(Errors==0), n=n(), Percent=`No errors` / n * 100) %>%
    reorder_systems()

  errorfree_files_overall <- errorfree_files_summary %>%
    group_by(System) %>%
    summarize(`No errors`=sum(`No errors`), n=sum(n), Percent=`No errors` / n * 100) %>%
    mutate(Dataset="Overall") %>%
    reorder_systems()

  errorfree_files_summary %>% bind_rows(errorfree_files_overall)
}

error_data_full <- read_summary_csv("error", col_types="ccccci")

# ES6 datasets
error_data <- error_data_full %>%
  filter_es6_renamed()

errors_per_file <- compute_errors_per_file(error_data, typecheck_data)
errorfree_files_summary <- compute_errorfree_files_summary(errors_per_file)

errorfree_files_summary.tex <- errorfree_files_summary %>%
  rename(errorfree=`No errors`, pct=Percent) %>%
  pivot_data() %>%
  format_numbers()

save.table(errorfree_files_summary.tex)

################################################################################
# Constants: min/max percent of files with no type errors
################################################################################

typecheck_file_pcts <- errorfree_files_summary %>%
  filter(Dataset == "Overall") %>%
  pull(Percent) %>%
  as.numeric() %>%
  round()

typecheckFileMin <- min(typecheck_file_pcts)
save.constant.txt(typecheckFileMin)

typecheckFileMax <- max(typecheck_file_pcts)
save.constant.txt(typecheckFileMax)

################################################################################
# Graph: percent of files with no errors
################################################################################

errorfree_files_summary.pdf <- percent_bar_graph(errorfree_files_summary) +
  labs(y="Files")

save.graph(errorfree_files_summary.pdf)

################################################################################
# Graph: percent of files with no errors per package
################################################################################

errorfree_per_package <- errors_per_file %>%
  group_by(System, Dataset, Package) %>%
  summarize(.groups="drop", `No errors`=sum(Errors==0), n=n(), Percent=`No errors` / n * 100) %>%
  reorder_systems()

errorfree_per_package.pdf <- errorfree_per_package %>%
  ggplot(aes(x=Percent)) +
  geom_histogram(binwidth=20, position=position_dodge()) +
  facet_grid(cols=vars(System)) +
  scale_x_continuous(name="Error-free files per package",
                     labels=scales::label_percent(scale=1)) +
  scale_y_continuous(name="Packages")

save.graph(errorfree_per_package.pdf, height=3.75)

################################################################################
# Graph: number/percent of "any" annotations, for files that type check
################################################################################

compute_annotations_per_file_summary <- function(annotations_data, errors_per_file) {
  # Annotations per file, given that the file has no errors
  annotations_per_file <- annotations_data %>%
    transmute(System, Dataset, Package, File, Trivial=as.integer(rowSums(.[5:7])), `Total annotations`) %>%
    inner_join(errors_per_file, by=c("System", "Dataset", "Package", "File")) %>%
    filter(Errors==0) %>%
    select(-Errors)

  annotations_per_file_summary <- annotations_per_file %>%
    group_by(System, Dataset) %>%
    summarize(.groups="drop", Trivial=sum(Trivial), n=sum(`Total annotations`), Percent=Trivial / n * 100) %>%
    reorder_systems()

  annotations_per_file_overall <- annotations_per_file_summary %>%
    group_by(System) %>%
    summarize(`Trivial`=sum(`Trivial`), n=sum(n), Percent=Trivial / n * 100) %>%
    mutate(Dataset="Overall") %>%
    reorder_systems()

  annotations_per_file_summary %>% bind_rows(annotations_per_file_overall)
}

annotations_data_full <- read_summary_csv("annotation", col_types="cccciiii")

annotations_data <- annotations_data_full %>%
  filter_es6_renamed()

annotations_per_file_summary <-
  compute_annotations_per_file_summary(annotations_data, errors_per_file)

annotations_per_file_summary.tex <- annotations_per_file_summary %>%
  rename(trivial=Trivial, pct=Percent) %>%
  pivot_data() %>%
  format_numbers()

save.table(annotations_per_file_summary.tex)

annotations_per_file_summary.pdf <- annotations_per_file_summary %>%
  percent_bar_graph() + labs(y="Annotations")

save.graph(annotations_per_file_summary.pdf)

################################################################################
# Table: number/percent of correct type annotations, wrt to ground truth
################################################################################

compute_accuracy_summary <- function(accuracy_data) {
  accuracy_summary <- accuracy_data %>%
    group_by(System, Dataset) %>%
    summarize(.groups="drop", Correct=sum(Correct), n=sum(n), Percent=Correct / n * 100) %>%
    reorder_systems()

  accuracy_overall <- accuracy_summary %>%
    group_by(System) %>%
    summarize(Correct=sum(Correct), n=sum(n), Percent=Correct / n * 100) %>%
    mutate(Dataset="Overall") %>%
    reorder_systems()

  accuracy_summary %>% bind_rows(accuracy_overall)
}

accuracy_data_full <- read_summary_csv("accuracy", col_types="ccciiiii") %>%
  filter(`Number of function signatures compared` > 0) %>%
  select(System, Dataset, Package, Correct=`Number of correct annotations`, n=`Number of annotations checked`)

accuracy_data <- accuracy_data_full %>%
  filter_es6_renamed()

accuracy_summary <- compute_accuracy_summary(accuracy_data)

accuracy_summary.tex <- accuracy_summary %>%
  rename(correct=Correct, pct=Percent) %>%
  pivot_data() %>%
  format_numbers()

save.table(accuracy_summary.tex)

################################################################################
# Graph: number/percent of correct type annotations, wrt to ground truth
################################################################################

accuracy_summary.pdf <- percent_bar_graph(accuracy_summary) +
  labs(y="Accuracy")

save.graph(accuracy_summary.pdf)

################################################################################
# Graph: error distribution, per package
################################################################################

errors_per_package <- errors_per_file %>%
  group_by(System, Dataset, Package) %>%
  summarize(.groups="drop", Errors=sum(Errors))

package_errors_cdf.pdf <- errors_per_package %>%
  ggplot(aes(x=Errors, color=System, linetype=System)) +
  scale_x_continuous(breaks=seq(0, 2500, by=500), labels=scales::label_comma()) +
  scale_y_continuous(name="Packages", breaks=seq(0, 1, by=0.2), labels=scales::percent) +
  stat_ecdf(size=1) +
  facet_wrap(vars(Dataset), ncol=2) +
  scale_color_brewer(palette=brewer, direction=-1)

save.graph(package_errors_cdf.pdf)

################################################################################
# Table: top 10 error codes
################################################################################

error_codes <- error_data %>%
  group_by(System, `Error code`) %>%
  summarize(.groups="drop", Count=sum(Count)) %>%
  reorder_systems() %>%
  pivot_wider(names_from=System, values_from=Count) %>%
  replace(is.na(.), 0) %>%
  mutate(Total=as.integer(rowSums(across(where(is.numeric)))))

error_codes.other <- error_codes %>%
  arrange(desc(Total)) %>%
  tail(nrow(.) - 10) %>%
  summarize(across(where(is.numeric), sum)) %>%
  mutate(`Error code`="Other")

error_codes_summary <- error_codes %>%
  arrange(desc(Total)) %>%
  head(10) %>%
  add_row(error_codes.other)

error_codes.total <- error_codes %>%
  summarize(across(where(is.numeric), sum)) %>%
  mutate(`Error code`="Total")

# Error messages from:
# https://github.com/microsoft/TypeScript/blob/v4.9.4/src/compiler/diagnosticMessages.json
error_codes_desc <- tribble(
  ~`Error code`, ~Description,
  "TS2339", "Property '{0}' does not exist on type '{1}.'",
  "TS2322", "Type '{0}' is not assignable to type '{1}'.",
  "TS2345", "Argument of type '{0}' is not assignable to parameter of type '{1}'.",
  "TS2304", "Cannot find name '{0}'.",
  "TS2554", "Expected {0} arguments, but got {1}.",
  "TS2349", "This expression is not callable.",
  "TS2551", "Property '{0}' does not exist on type '{1}'. Did you mean '{2}'?",
  "TS2307", "Cannot find module '{0}' or its corresponding type declarations.",
  "TS4078", "Parameter '{0}' of exported function has or is using private name '{1}'.",
  "TS2367", "This comparison appears to be unintentional because the types '{0}' and '{1}' have no overlap.",
  "Other", "",
  "Total", "")

error_codes_summary.tex <- error_codes_summary %>%
  add_row(error_codes.total) %>%
  inner_join(error_codes_desc, by="Error code") %>%
  select(`Error code`, Description, names(SYSTEMS)) %>%
  format_numbers()
stopifnot(nrow(error_codes_summary.tex) == 12)

save.table(error_codes_summary.tex)

################################################################################
# Graph: top 10 error codes
################################################################################

error_codes_graph <- error_codes_summary %>%
  select(-Total) %>%
  pivot_longer(cols=-1, names_to="System", values_to="Count") %>%
  reorder_systems()

error_codes.pdf <- error_codes_graph %>%
  ggplot(aes(x=`Error code`, y=Count)) +
  geom_bar(stat="identity") +
  facet_grid(cols=vars(System)) +
  theme(axis.text.x=element_text(angle=45, vjust=0.5, size=8),
        panel.grid.major.x=element_blank()) +
  scale_x_discrete(limits=error_codes_summary$`Error code`) +
  scale_y_continuous(labels=scales::label_comma())

save.graph(error_codes.pdf, height=3.75)

################################################################################
# Table: percent of packages that type check, pre-es6 vs es6
################################################################################

typecheck_data_pre <- typecheck_data_full %>% filter_pre_es6_renamed()

typecheck_comparison.tex <- typecheck_data_pre %>%
  compute_typecheck_summary() %>%
  inner_join(typecheck_summary,
             by=c("System", "Dataset"),
             suffix=c(".pre", ".es6")) %>%
  select(System, Dataset, pct.pre=Percent.pre, pct.es6=Percent.es6) %>%
  pivot_data() %>%
  format_numbers()

save.table(typecheck_comparison.tex)

################################################################################
# Table: percent of files with no errors, pre-es6 vs es6
################################################################################

error_data_pre <- error_data_full %>% filter_pre_es6_renamed()

errorfree_files_comparison.tex <-
  compute_errors_per_file(error_data_pre, typecheck_data_pre) %>%
  compute_errorfree_files_summary() %>%
  inner_join(errorfree_files_summary,
             by=c("System", "Dataset"),
             suffix=c(".pre", ".es6")) %>%
  select(System, Dataset, pct.pre=Percent.pre, pct.es6=Percent.es6) %>%
  pivot_data() %>%
  format_numbers()

save.table(errorfree_files_comparison.tex)

################################################################################
# Table: percent of correct type annotations, pre-es6 vs es6
################################################################################

accuracy_comparison.tex <- accuracy_data_full %>%
  filter_pre_es6_renamed() %>%
  compute_accuracy_summary() %>%
  inner_join(accuracy_summary,
             by=c("System", "Dataset"),
             suffix=c(".pre", ".es6")) %>%
  select(System, Dataset, pct.pre=Percent.pre, pct.es6=Percent.es6) %>%
  pivot_data() %>%
  format_numbers()

save.table(accuracy_comparison.tex)

################################################################################
# Graph: comparing type checking, before and after es6 transformation
################################################################################

typechecks_before_after <-
  inner_join(typecheck_data_pre, typecheck_data,
             by=c("System", "Dataset", "Package"),
             suffix=c(".pre", ".es6")) %>%
  reorder_systems() %>%
  unite(`Type checks.pre`, `Type checks.es6`, col=typechecks, sep="") %>%
  filter(typechecks != "00") %>%
  mutate(typechecks = case_when(typechecks == "11" ~ "Both type check",
                                typechecks == "10" ~ "Type checks before",
                                typechecks == "01" ~ "Type checks after")) %>%
  group_by(System, Dataset, typechecks) %>%
  summarize(.groups="drop", Packages=n())

# Reorder typechecks column
typechecks_before_after$typechecks <- factor(typechecks_before_after$typechecks,
                                             levels=c("Both type check", "Type checks before", "Type checks after"))

typechecks_before_after.pdf <- typechecks_before_after %>%
  ggplot(aes(x=System, y=Packages, fill=typechecks)) +
  geom_bar(stat="identity", position=position_dodge()) +
  facet_wrap(vars(Dataset), ncol=2) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_text(angle=30, vjust=0.5)) +
  scale_fill_brewer(palette=brewer, direction=-1)

save.graph(typechecks_before_after.pdf)
