#!/usr/bin/env Rscript

suppressMessages(library(tidyverse))
suppressMessages(library(extrafont))
suppressMessages(loadfonts())

data_dir <- commandArgs(trailingOnly=TRUE)
figures_dir <- paste0(data_dir, "/figures")
csv_dir <- paste0(data_dir, "/csv")

if (!file.exists(figures_dir)) {
    dir.create(figures_dir)
}

################################################################################
# Initialize theme
################################################################################

theme_set(
  theme_bw() +
    theme(text = element_text(family="CM Roman", size=12),
          panel.grid.major = element_line(color="gray", linewidth=0.2),
          panel.grid.minor = element_line(color="gray", linewidth=0.2, linetype="dotted"),
          axis.ticks = element_line(linewidth=0.05),
          legend.margin = margin(0, 0, 0, 0),
          legend.position = "bottom",
          legend.key.size = unit(0.5, "cm"),
          legend.title = element_blank()))

brewer3 <- "Blues"
brewer5 <- "Blues"

################################################################################
# Helper functions
################################################################################
constant.tex <- paste0(figures_dir, "/", "constants.tex")
cat("% DO NOT MODIFY: this file is generated by an R script\n", file=constant.tex)

save.constant <- function(constant) {
  output <- paste0("\\newcommand{\\", substitute(constant), "}{", constant, "}\n")
  cat("Writing constant", substitute(constant), "=", constant, "to", constant.tex, "\n")
  cat(output, file=constant.tex, append=TRUE)
}

# Outputs a tibble in LaTeX format (minus the headers)
# Essentially just adds the & between columns and \\ at the end of each row
save.table <- function(table) {
  file <- paste0(figures_dir, "/", substitute(table))
  cat("Writing table:", file, "\n")
  cat("% DO NOT MODIFY: this file is generated by an R script\n", file=file)
  for (row in 1:nrow(table)) {
    for (col in 1:ncol(table)) {
      cat(table[[row, col]], file=file, append=TRUE)
      if (col < ncol(table)) cat(" & ", file=file, append=TRUE)
    }
    cat(" \\\\\n", file=file, append=TRUE)
  }
}

save.graph <- function(plot, width=7.5, height=5) {
  file <- paste0(figures_dir, "/", substitute(plot))
  cat("Writing plot:", file, "\n")
  ggsave(file, plot=plot, width=width, height=height)
}

rename_datasets <- function(tbl) {
  mutate(tbl, dataset = case_when(str_starts(dataset, "top1k-typed-nodeps") ~ "DefinitelyTyped, no deps",
                                  str_starts(dataset, "top1k-typed-with-typed-deps") ~ "DefinitelyTyped, with deps",
                                  str_starts(dataset, "top1k-untyped-nodeps") ~ "Never typed, no deps",
                                  str_starts(dataset, "top1k-untyped-with-typed-deps") ~ "Never typed, with deps"))
}

################################################################################
# Table: package counts, file counts, and lines of code for each dataset
################################################################################

loc_per_file <- read_csv(paste0(csv_dir, "/", "file_loc.csv"), col_types="ccci") %>%
  rename(dataset=1, package=2, file=3, loc=4) %>%
  filter(str_ends(dataset, "es6")) %>%
  rename_datasets()

loc_per_package <- loc_per_file %>%
  group_by(dataset, package) %>%
  summarize(.groups="drop", loc=sum(loc))

dataset_summary <- loc_per_file %>%
  group_by(dataset, package) %>%
  summarize(.groups="drop_last", n.files=n(), loc=sum(loc)) %>%
  summarize(n.packages=n(), n.files=sum(n.files), loc=sum(loc))

totalpkgs <- dataset_summary %>% pull(n.packages) %>% sum()
save.constant(totalpkgs)

dataset_summary.tex <-
  dataset_summary %>%
  add_row(dataset = "Overall",
          n.packages = sum(.$n.packages),
          n.files = sum(.$n.files),
          loc = sum(.$loc)) %>%
  mutate(dataset = ifelse(str_detect(dataset, "Overall"), "\\textbf{Overall}", dataset)) %>%
  mutate(across(where(is.integer), scales::label_comma()))

save.table(dataset_summary.tex)

################################################################################
# Graph: distribution of package lines of code
################################################################################

package_loc_cdf.pdf <-
  ggplot(loc_per_package, aes(x=loc)) +
  scale_x_continuous(name="Lines of code", breaks=seq(0, 10000, by=2000)) +
  scale_y_continuous(name="Packages", breaks=seq(0, 1, by=0.2), labels=scales::percent) +
  stat_ecdf()

save.graph(package_loc_cdf.pdf, height=3.75)

################################################################################
# Table: number/percent of packages that type check
################################################################################

typecheck_data <- read_csv(paste0(csv_dir, "/", "typecheck_summary.csv"), col_types="cciii") %>%
  rename(dataset=1, package=2, dt=3, ln=4, ic=5)
typecheck_data.es6 <- typecheck_data %>% filter(str_ends(dataset, "es6"))

typecheck_summary.dt <- typecheck_data.es6 %>%
  group_by(dataset) %>%
  drop_na(dt) %>%
  summarize(dt.typechecks = sum(dt), dt.n = n(), dt.pct = dt.typechecks / dt.n * 100)

typecheck_summary.ln <- typecheck_data.es6 %>%
  group_by(dataset) %>%
  drop_na(ln) %>%
  summarize(ln.typechecks = sum(ln), ln.n = n(), ln.pct = ln.typechecks / ln.n * 100)

typecheck_summary.ic <- typecheck_data.es6 %>%
  group_by(dataset) %>%
  drop_na(ic) %>%
  summarize(ic.typechecks = sum(ic), ic.n = n(), ic.pct = ic.typechecks / ic.n * 100)

typecheck.pct <- typecheck_summary.dt %>%
  inner_join(typecheck_summary.ln, by="dataset") %>%
  inner_join(typecheck_summary.ic, by="dataset") %>%
  rename_datasets() %>%
  add_row(dataset = "Overall",
          dt.typechecks = sum(.$dt.typechecks), dt.n = sum(.$dt.n),
          ln.typechecks = sum(.$ln.typechecks), ln.n = sum(.$ln.n),
          ic.typechecks = sum(.$ic.typechecks), ic.n = sum(.$ic.n),
          dt.pct = dt.typechecks / dt.n * 100,
          ln.pct = ln.typechecks / ln.n * 100,
          ic.pct = ic.typechecks / ic.n * 100)

pkg_typechecks.tex <-
  typecheck.pct %>%
  mutate(dataset = ifelse(str_detect(dataset, "Overall"), "\\textbf{Overall}", dataset)) %>%
  mutate(across(where(is.double), scales::label_number(accuracy=0.1))) %>%
  mutate(across(where(is.integer), scales::label_comma()))

save.table(pkg_typechecks.tex)

################################################################################
# Constants: min/max percent of packages that type check
################################################################################

typecheck_overall_pcts = typecheck.pct %>%
  filter(dataset=="Overall") %>%
  select(dt=dt.pct, ln=ln.pct, ic=ic.pct) %>%
  as.numeric() %>%
  round()

typecheckPkgMin <- min(typecheck_overall_pcts)
save.constant(typecheckPkgMin)

typecheckPkgMax <- max(typecheck_overall_pcts)
save.constant(typecheckPkgMax)

################################################################################
# Graph: percent of packages that type check
################################################################################

typecheck.graph.data <- typecheck.pct %>%
  select(dataset, deeptyper=dt.pct, lambdanet=ln.pct, incoder=ic.pct) %>%
  pivot_longer(cols=2:4, names_to="system", values_to="pct")

pkg_typechecks.pdf <-
  ggplot(typecheck.graph.data, aes(x=system, y=pct, fill=dataset)) +
  geom_bar(stat="identity", position=position_dodge()) +
  theme(axis.title.x=element_blank()) +
  scale_x_discrete(limits=c("deeptyper","lambdanet","incoder"),
                   labels=c("deeptyper"="DeepTyper","lambdanet"="LambdaNet","incoder"="InCoder")) +
  scale_y_continuous(name="Packages",
                     limits=c(0,100),
                     breaks=seq(0, 100, by=20),
                     labels=scales::label_percent(scale=1)) +
  guides(fill = guide_legend(nrow=2)) +
  scale_fill_brewer(palette=brewer5, direction=-1)

save.graph(pkg_typechecks.pdf)

################################################################################
# Table: number/percent of files with no errors
################################################################################

errors_per_file.dt <- read_csv(paste0(csv_dir, "/", "errors_per_file.dt.csv"), col_types="ccci") %>%
  rename(dataset=1, package=2, file=3, dt=4)
errors_per_file_summary.dt <- errors_per_file.dt %>%
  filter(str_ends(dataset, "es6")) %>%
  group_by(dataset) %>%
  summarize(dt.no_errors = sum(dt == 0), dt.n = n(), dt.pct = dt.no_errors / dt.n * 100)

errors_per_file.ln <- read_csv(paste0(csv_dir, "/", "errors_per_file.ln.csv"), col_types="ccci") %>%
  rename(dataset=1, package=2, file=3, ln=4)
errors_per_file_summary.ln <- errors_per_file.ln %>%
  filter(str_ends(dataset, "es6")) %>%
  group_by(dataset) %>%
  summarize(ln.no_errors = sum(ln == 0), ln.n = n(), ln.pct = ln.no_errors / ln.n * 100)

errors_per_file.ic <- read_csv(paste0(csv_dir, "/", "errors_per_file.ic.csv"), col_types="ccci") %>%
  rename(dataset=1, package=2, file=3, ic=4)
errors_per_file_summary.ic <- errors_per_file.ic %>%
  filter(str_ends(dataset, "es6")) %>%
  group_by(dataset) %>%
  summarize(ic.no_errors = sum(ic == 0), ic.n = n(), ic.pct = ic.no_errors / ic.n * 100)

files_no_errors.pct <- errors_per_file_summary.dt %>%
  inner_join(errors_per_file_summary.ln, by="dataset") %>%
  inner_join(errors_per_file_summary.ic, by="dataset") %>%
  rename_datasets() %>%
  add_row(dataset = "Overall",
          dt.no_errors = sum(.$dt.no_errors), dt.n = sum(.$dt.n),
          ln.no_errors = sum(.$ln.no_errors), ln.n = sum(.$ln.n),
          ic.no_errors = sum(.$ic.no_errors), ic.n = sum(.$ic.n),
          dt.pct = dt.no_errors / dt.n * 100,
          ln.pct = ln.no_errors / ln.n * 100,
          ic.pct = ic.no_errors / ic.n * 100)

files_no_errors.tex <-
  files_no_errors.pct %>%
  mutate(dataset = ifelse(str_detect(dataset, "Overall"), "\\textbf{Overall}", dataset)) %>%
  mutate(across(where(is.double), scales::label_number(accuracy=0.1))) %>%
  mutate(across(where(is.integer), scales::label_comma()))

save.table(files_no_errors.tex)

################################################################################
# Constants: min/max percent of files with no type errors
################################################################################

typecheck_file_pcts = files_no_errors.pct %>%
  filter(dataset=="Overall") %>%
  select(dt=dt.pct, ln=ln.pct, ic=ic.pct) %>%
  as.numeric() %>%
  round()

typecheckFileMin <- min(typecheck_file_pcts)
save.constant(typecheckFileMin)

typecheckFileMax <- max(typecheck_file_pcts)
save.constant(typecheckFileMax)

################################################################################
# Graph: percent of files with no errors
################################################################################

files_no_errors.graph.data <- files_no_errors.pct %>%
  select(dataset, deeptyper=dt.pct, lambdanet=ln.pct, incoder=ic.pct) %>%
  pivot_longer(cols=2:4, names_to="system", values_to="pct")

files_no_errors.pdf <-
  ggplot(files_no_errors.graph.data, aes(x=system, y=pct, fill=dataset)) +
  geom_bar(stat="identity", position=position_dodge()) +
  theme(axis.title.x=element_blank()) +
  scale_x_discrete(limits=c("deeptyper","lambdanet","incoder"),
                   labels=c("deeptyper"="DeepTyper","lambdanet"="LambdaNet","incoder"="InCoder")) +
  scale_y_continuous(name="Files",
                     limits=c(0,100),
                     breaks=seq(0, 100, by=20),
                     labels=scales::label_percent(scale=1)) +
  guides(fill = guide_legend(nrow=2)) +
  scale_fill_brewer(palette=brewer5, direction=-1)

save.graph(files_no_errors.pdf)

################################################################################
# Graph: percent of files with no errors per package
################################################################################

pct_errorfree_per_package.dt <- errors_per_file.dt %>%
  filter(str_ends(dataset, "es6")) %>%
  group_by(dataset, package) %>%
  summarize(.groups="drop", dt.no_errors = sum(dt == 0), dt.nfiles = n(), dt.pct = dt.no_errors / dt.nfiles * 100)

pct_errorfree_per_package.ln <- errors_per_file.ln %>%
  filter(str_ends(dataset, "es6")) %>%
  group_by(dataset, package) %>%
  summarize(.groups="drop", ln.no_errors = sum(ln == 0), ln.nfiles = n(), ln.pct = ln.no_errors / ln.nfiles * 100)

pct_errorfree_per_package.ic <- errors_per_file.ic %>%
  filter(str_ends(dataset, "es6")) %>%
  group_by(dataset, package) %>%
  summarize(.groups="drop", ic.no_errors = sum(ic == 0), ic.nfiles = n(), ic.pct = ic.no_errors / ic.nfiles * 100)

errorfree_per_package <- pct_errorfree_per_package.dt %>%
  full_join(pct_errorfree_per_package.ln, by=c("dataset", "package")) %>%
  full_join(pct_errorfree_per_package.ic, by=c("dataset", "package")) %>%
  select(dataset, package, deeptyper=dt.pct, lambdanet=ln.pct, incoder=ic.pct) %>%
  pivot_longer(cols=3:5, names_to="system", values_to="pct") %>%
  drop_na()

# Reorder factors
errorfree_per_package$system <- factor(errorfree_per_package$system,
                                       levels=c("deeptyper", "lambdanet", "incoder"))

errorfree_per_package.pdf <-
  ggplot(errorfree_per_package, aes(x=pct)) +
  geom_histogram(binwidth=20, position=position_dodge()) +
  facet_grid(cols=vars(system),
             labeller=labeller(system=c("deeptyper"="DeepTyper","lambdanet"="LambdaNet","incoder"="InCoder"))) +
  scale_x_continuous(name="Error\u00adfree files per package",
                     labels=scales::label_percent(scale=1)) +
  scale_y_continuous(name="Packages")

save.graph(errorfree_per_package.pdf, height=3.75)

################################################################################
# Table: number/percent of correct type annotations, wrt to ground truth
################################################################################

accuracy_data <- read_csv(paste0(csv_dir, "/", "accuracy_summary.csv"), col_types="ccciiiii") %>%
  rename(system=1, dataset=2, package=3, sigs=4, correct=5, inferred_anys=6, n=7, truth_anys=8)
accuracy_data.es6 <- accuracy_data %>% filter(str_ends(dataset, "es6"))

accuracy_summary.dt <- accuracy_data.es6 %>%
  filter(system == "deeptyper") %>%
  select(2:8) %>%
  filter(sigs > 0) %>%
  group_by(dataset) %>%
  summarize(dt.correct = sum(correct), dt.n = sum(n), dt.accuracy = dt.correct / dt.n * 100,
            dt.sigs = sum(sigs), dt.inferred_anys = sum(inferred_anys), dt.truth_anys = sum(truth_anys))

accuracy_summary.ln <- accuracy_data.es6 %>%
  filter(system == "lambdanet") %>%
  select(2:8) %>%
  filter(sigs > 0) %>%
  group_by(dataset) %>%
  summarize(ln.correct = sum(correct), ln.n = sum(n), ln.accuracy = ln.correct / ln.n * 100,
            ln.sigs = sum(sigs), ln.inferred_anys = sum(inferred_anys), ln.truth_anys = sum(truth_anys))

accuracy_summary.ic <- accuracy_data.es6 %>%
  filter(system == "incoder") %>%
  select(2:8) %>%
  filter(sigs > 0) %>%
  group_by(dataset) %>%
  summarize(ic.correct = sum(correct), ic.n = sum(n), ic.accuracy = ic.correct / ic.n * 100,
            ic.sigs = sum(sigs), ic.inferred_anys = sum(inferred_anys), ic.truth_anys = sum(truth_anys))

accuracy.pct.full <- accuracy_summary.dt %>%
  inner_join(accuracy_summary.ln, by="dataset") %>%
  inner_join(accuracy_summary.ic, by="dataset") %>%
  rename_datasets() %>%
  add_row(dataset = "Overall",
          dt.correct = sum(.$dt.correct), dt.n = sum(.$dt.n),
          ln.correct = sum(.$ln.correct), ln.n = sum(.$ln.n),
          ic.correct = sum(.$ic.correct), ic.n = sum(.$ic.n),
          dt.accuracy = dt.correct / dt.n * 100,
          ln.accuracy = ln.correct / ln.n * 100,
          ic.accuracy = ic.correct / ic.n * 100,
          dt.sigs = sum(.$dt.sigs), dt.inferred_anys = sum(.$dt.inferred_anys), dt.truth_anys = sum(.$dt.truth_anys),
          ln.sigs = sum(.$ln.sigs), ln.inferred_anys = sum(.$ln.inferred_anys), ln.truth_anys = sum(.$ln.truth_anys),
          ic.sigs = sum(.$ic.sigs), ic.inferred_anys = sum(.$ic.inferred_anys), ic.truth_anys = sum(.$ic.truth_anys))

accuracy.pct <- accuracy.pct.full %>%
  select(dataset,
         dt.correct, dt.n, dt.accuracy,
         ln.correct, ln.n, ln.accuracy,
         ic.correct, ic.n, ic.accuracy)

accuracy.tex <-
  accuracy.pct %>%
  mutate(dataset = ifelse(str_detect(dataset, "Overall"), "\\textbf{Overall}", dataset)) %>%
  mutate(across(where(is.double), scales::label_number(accuracy=0.1))) %>%
  mutate(across(where(is.integer), scales::label_comma()))

save.table(accuracy.tex)

################################################################################
# Graph: number/percent of correct type annotations, wrt to ground truth
################################################################################

accuracy.graph.data <- accuracy.pct %>%
  select(dataset, deeptyper=dt.accuracy, lambdanet=ln.accuracy, incoder=ic.accuracy) %>%
  pivot_longer(cols=2:4, names_to="system", values_to="accuracy")

accuracy.pdf <-
  ggplot(accuracy.graph.data, aes(x=system, y=accuracy, fill=dataset)) +
  geom_bar(stat="identity", position=position_dodge()) +
  theme(axis.title.x=element_blank()) +
  scale_x_discrete(limits=c("deeptyper","lambdanet","incoder"),
                   labels=c("deeptyper"="DeepTyper","lambdanet"="LambdaNet","incoder"="InCoder")) +
  scale_y_continuous(name="Accuracy",
                     limits=c(0,100),
                     breaks=seq(0, 100, by=20),
                     labels=scales::label_percent(scale=1)) +
  scale_fill_brewer(palette=brewer3, direction=-1)

save.graph(accuracy.pdf)

################################################################################
# Graph: error distribution, per package
################################################################################

errors_per_file <- errors_per_file.dt %>%
  full_join(errors_per_file.ln, by=c("dataset", "package", "file")) %>%
  full_join(errors_per_file.ic, by=c("dataset", "package", "file")) %>%
  filter(str_ends(dataset, "es6")) %>%
  rename_datasets()

errors_per_package <- errors_per_file %>%
  group_by(dataset, package) %>%
  summarize(.groups="drop", dt=sum(dt), ln=sum(ln), ic=sum(ic)) %>%
  rename(deeptyper=dt, lambdanet=ln, incoder=ic) %>%
  pivot_longer(cols=3:5, names_to="system", values_to="errors") %>%
  drop_na(errors)

# Reorder and rename factors
errors_per_package$system <- errors_per_package$system %>%
  case_match("deeptyper" ~ "DeepTyper",
             "lambdanet" ~ "LambdaNet",
             "incoder" ~ "InCoder") %>%
  factor(levels=c("DeepTyper", "LambdaNet", "InCoder"))

error_cdf.pdf <-
  ggplot(errors_per_package, aes(x=errors, color=system, linetype=system)) +
  scale_x_continuous(name="Errors", breaks=seq(0, 2500, by=500)) +
  scale_y_continuous(name="Packages", breaks=seq(0, 1, by=0.2), labels=scales::percent) +
  stat_ecdf() +
  facet_wrap(vars(dataset), ncol=2) +
  scale_color_brewer(palette=brewer3, direction=-1)

save.graph(error_cdf.pdf)

################################################################################
# Graph: number/percent of "any" annotations, for files that type check
################################################################################

anns_per_file.dt <- read_csv(paste0(csv_dir, "/", "annotations_per_file.dt.csv"), col_types="ccciiii") %>%
  rename(dataset=1, package=2, file=3, anys=4, arrays=5, functions=6, total=7) %>%
  filter(str_ends(dataset, "es6")) %>%
  rename_datasets()

anns_per_file.ln <- read_csv(paste0(csv_dir, "/", "annotations_per_file.ln.csv"), col_types="ccciiii") %>%
  rename(dataset=1, package=2, file=3, anys=4, arrays=5, functions=6, total=7) %>%
  filter(str_ends(dataset, "es6")) %>%
  rename_datasets()

anns_per_file.ic <- read_csv(paste0(csv_dir, "/", "annotations_per_file.ic.csv"), col_types="ccciiii") %>%
  rename(dataset=1, package=2, file=3, anys=4, arrays=5, functions=6, total=7) %>%
  filter(str_ends(dataset, "es6")) %>%
  rename_datasets()

anns_per_file.dt.file <-
  inner_join(
    anns_per_file.dt,
    errors_per_file %>% filter(dt == 0) %>% select(dataset, package, file),
    by=c("dataset", "package", "file"))

anns_per_file.ln.file <-
  inner_join(
    anns_per_file.ln,
    errors_per_file %>% filter(ln == 0) %>% select(dataset, package, file),
    by=c("dataset", "package", "file"))

anns_per_file.ic.file <-
  inner_join(
    anns_per_file.ic,
    errors_per_file %>% filter(ic == 0) %>% select(dataset, package, file),
    by=c("dataset", "package", "file"))

anns_dataset_summary.dt.file <- anns_per_file.dt.file %>%
  group_by(dataset) %>%
  summarize(anys = sum(anys), arrays = sum(arrays), functions = sum(functions),
            generic = anys + arrays + functions,
            total = sum(total),
            pct = generic / total * 100)

anns_dataset_summary.ln.file <- anns_per_file.ln.file %>%
  group_by(dataset) %>%
  summarize(anys = sum(anys), arrays = sum(arrays), functions = sum(functions),
            generic = anys + arrays + functions,
            total = sum(total),
            pct = generic / total * 100)

anns_dataset_summary.ic.file <- anns_per_file.ic.file %>%
  group_by(dataset) %>%
  summarize(anys = sum(anys), arrays = sum(arrays), functions = sum(functions),
            generic = anys + arrays + functions,
            total = sum(total),
            pct = generic / total * 100)

anns_dataset_summary.file <-
  mutate(anns_dataset_summary.dt.file, system="deeptyper", .before=1) %>%
  add_row(
    mutate(anns_dataset_summary.ln.file, system="lambdanet", .before=1)) %>%
  add_row(
    mutate(anns_dataset_summary.ic.file, system="incoder", .before=1))

anns_dataset_summary.file.wide <- anns_dataset_summary.file %>%
  select(system, dataset, generic, total, pct) %>%
  pivot_wider(names_from=system, values_from=c(generic, total, pct)) %>%
  select(dataset,
         dt.generic = generic_deeptyper, dt.n = total_deeptyper, dt.pct = pct_deeptyper,
         ln.generic = generic_lambdanet, ln.n = total_lambdanet, ln.pct = pct_lambdanet,
         ic.generic = generic_incoder, ic.n = total_incoder, ic.pct = pct_incoder) %>%
  add_row(dataset = "Overall",
          dt.generic = sum(.$dt.generic), dt.n = sum(.$dt.n),
          ln.generic = sum(.$ln.generic), ln.n = sum(.$ln.n),
          ic.generic = sum(.$ic.generic), ic.n = sum(.$ic.n),
          dt.pct = dt.generic / dt.n * 100,
          ln.pct = ln.generic / ln.n * 100,
          ic.pct = ic.generic / ic.n * 100)

ann_dataset.file.graph.data <- anns_dataset_summary.file.wide %>%
  select(dataset, deeptyper=dt.pct, lambdanet=ln.pct, incoder=ic.pct) %>%
  pivot_longer(cols=2:4, names_to="system", values_to="pct")

errorfree_files_anys.pdf <-
  ggplot(ann_dataset.file.graph.data, aes(x=system, y=pct, fill=dataset)) +
  geom_bar(stat="identity", position=position_dodge()) +
  theme(axis.title.x=element_blank()) +
  scale_x_discrete(limits=c("deeptyper","lambdanet","incoder"),
                   labels=c("deeptyper"="DeepTyper","lambdanet"="LambdaNet","incoder"="InCoder")) +
  scale_y_continuous(name="Annotations",
                     limits=c(0, 100),
                     breaks=seq(0, 100, by=20),
                     labels=scales::label_percent(scale=1)) +
  guides(fill = guide_legend(nrow=2)) +
  scale_fill_brewer(palette=brewer5, direction=-1)

save.graph(errorfree_files_anys.pdf)

################################################################################
# Table: top 10 error codes
################################################################################

error_codes_file.dt <- read_csv(paste0(csv_dir, "/", "error_codes.dt.csv"), col_types="cccci") %>%
  rename(dataset=1, package=2, file=3, error=4, count=5) %>%
  filter(str_ends(dataset, "es6")) %>%
  rename_datasets()
error_codes_summary.dt <- error_codes_file.dt %>%
  group_by(dataset, error) %>%
  summarize(.groups="drop", dt.count=sum(count))

error_codes_file.ln <- read_csv(paste0(csv_dir, "/", "error_codes.ln.csv"), col_types="cccci") %>%
  rename(dataset=1, package=2, file=3, error=4, count=5) %>%
  filter(str_ends(dataset, "es6")) %>%
  rename_datasets()
error_codes_summary.ln <- error_codes_file.ln %>%
  group_by(dataset, error) %>%
  summarize(.groups="drop", ln.count=sum(count))

error_codes_file.ic <- read_csv(paste0(csv_dir, "/", "error_codes.ic.csv"), col_types="cccci") %>%
  rename(dataset=1, package=2, file=3, error=4, count=5) %>%
  filter(str_ends(dataset, "es6")) %>%
  rename_datasets()
error_codes_summary.ic <- error_codes_file.ic %>%
  group_by(dataset, error) %>%
  summarize(.groups="drop", ic.count=sum(count))

error_codes_summary <- error_codes_summary.dt %>%
  full_join(error_codes_summary.ln, by=c("dataset","error")) %>%
  full_join(error_codes_summary.ic, by=c("dataset","error")) %>%
  replace_na(list(dt.count=0, ln.count=0, ic.count=0)) %>%
  group_by(error) %>%
  summarize(.groups="drop", dt=sum(dt.count), ln=sum(ln.count), ic=sum(ic.count), total=dt+ln+ic)

# Error messages from:
# https://github.com/Microsoft/TypeScript/blob/v4.7.3/src/compiler/diagnosticMessages.json
error_codes_desc <-
  tribble(
    ~error, ~desc,
    "TS2339", "Property '{0}' does not exist on type '{1}.'",
    "TS2322", "Type '{0}' is not assignable to type '{1}'.",
    "TS2345", "Argument of type '{0}' is not assignable to parameter of type '{1}'.",
    "TS2304", "Cannot find name '{0}'.",
    "TS2554", "Expected {0} arguments, but got {1}.",
    "TS2349", "This expression is not callable.",
    "TS2367", "This condition will always return '{0}' since the types '{1}' and '{2}' have no overlap.",
    "TS2307", "Cannot find module '{0}' or its corresponding type declarations.",
    "TS2551", "Property '{0}' does not exist on type '{1}'. Did you mean '{2}'?",
    "TS2314", "Generic type '{0}' requires {1} type argument(s).",
    "Other", "",
    "Total", "")

error_codes_summary.10.rest <- error_codes_summary %>%
  arrange(desc(total)) %>%
  tail(nrow(.)-10)
error_codes_summary.10 <- error_codes_summary %>%
  arrange(desc(total)) %>%
  head(10) %>%
  add_row(error = "Other",
          dt = sum(error_codes_summary.10.rest$dt),
          ln = sum(error_codes_summary.10.rest$ln),
          ic = sum(error_codes_summary.10.rest$ic),
          total = sum(error_codes_summary.10.rest$total))

error_codes.tex <- error_codes_summary.10 %>%
  add_row(error = "Total",
          dt = sum(.$dt),
          ln = sum(.$ln),
          ic = sum(.$ic)) %>%
  left_join(error_codes_desc, by="error") %>%
  select(error, desc, dt, ln, ic) %>%
  mutate(desc = str_replace_all(desc, r"(\{)", r"(\\{)")) %>%
  mutate(desc = str_replace_all(desc, r"(\})", r"(\\})")) %>%
  mutate(error = ifelse(str_detect(error, "Total"), "\\textbf{Total}", error)) %>%
  mutate(across(where(is.integer), scales::label_comma()))

save.table(error_codes.tex)

################################################################################
# Graph: top 10 error codes
################################################################################

error_codes_summary.10.long <- error_codes_summary.10 %>%
  transmute(error, deeptyper=dt, lambdanet=ln, incoder=ic) %>%
  pivot_longer(cols=2:4, names_to="system", values_to="count")

# Reorder factors
error_codes_summary.10.long$system <- factor(error_codes_summary.10.long$system,
                                             levels=c("deeptyper", "lambdanet", "incoder"))

error_codes.pdf <-
  ggplot(error_codes_summary.10.long, aes(x=error, y=count)) +
  geom_bar(stat="identity") +
  facet_grid(cols=vars(system),
             labeller=labeller(system=c("deeptyper"="DeepTyper","lambdanet"="LambdaNet","incoder"="InCoder"))) +
  theme(axis.text.x = element_text(angle=45, vjust=0.5, size=8),
        panel.grid.major.x = element_blank()) +
  scale_x_discrete(name="Error codes", limits=error_codes_summary.10$error) +
  scale_y_continuous(name="Count", labels=scales::label_comma())

save.graph(error_codes.pdf, height=3.75)

################################################################################
# Table: percent of packages that type check, pre-es6 vs es6
################################################################################

typecheck_data.pre <- typecheck_data %>% filter(!str_ends(dataset, "es6"))

typecheck_summary.pre.dt <- typecheck_data.pre %>%
  group_by(dataset) %>%
  drop_na(dt) %>%
  summarize(dt.typechecks = sum(dt), dt.n = n(), dt.pct = dt.typechecks / dt.n * 100)

typecheck_summary.pre.ln <- typecheck_data.pre %>%
  group_by(dataset) %>%
  drop_na(ln) %>%
  summarize(ln.typechecks = sum(ln), ln.n = n(), ln.pct = ln.typechecks / ln.n * 100)

typecheck_summary.pre.ic <- typecheck_data.pre %>%
  group_by(dataset) %>%
  drop_na(ic) %>%
  summarize(ic.typechecks = sum(ic), ic.n = n(), ic.pct = ic.typechecks / ic.n * 100)

typecheck.pre.pct <- typecheck_summary.pre.dt %>%
  inner_join(typecheck_summary.pre.ln, by="dataset") %>%
  inner_join(typecheck_summary.pre.ic, by="dataset") %>%
  rename_datasets() %>%
  add_row(dataset = "Overall",
          dt.typechecks = sum(.$dt.typechecks), dt.n = sum(.$dt.n),
          ln.typechecks = sum(.$ln.typechecks), ln.n = sum(.$ln.n),
          ic.typechecks = sum(.$ic.typechecks), ic.n = sum(.$ic.n),
          dt.pct = dt.typechecks / dt.n * 100,
          ln.pct = ln.typechecks / ln.n * 100,
          ic.pct = ic.typechecks / ic.n * 100)

typecheck_comparison <-
  inner_join(
    typecheck.pre.pct %>% select(dataset, ends_with("pct")),
    typecheck.pct %>% select(dataset, ends_with("pct")),
    by="dataset",
    suffix=c(".pre", ".es6")) %>%
  select(dataset,
         dt.pre=dt.pct.pre, dt.es6=dt.pct.es6,
         ln.pre=ln.pct.pre, ln.es6=ln.pct.es6,
         ic.pre=ic.pct.pre, ic.es6=ic.pct.es6)

typecheck_comparison.tex <-
  typecheck_comparison %>%
  mutate(dataset = ifelse(str_detect(dataset, "Overall"), "\\textbf{Overall}", dataset)) %>%
  mutate(across(where(is.double), scales::label_number(accuracy=0.1)))

save.table(typecheck_comparison.tex)

################################################################################
# Table: percent of files with no errors, pre-es6 vs es6
################################################################################

errors_per_file_summary.pre.dt <- errors_per_file.dt %>%
  filter(!str_ends(dataset, "es6")) %>%
  group_by(dataset) %>%
  summarize(dt.no_errors = sum(dt == 0), dt.n = n(), dt.pct = dt.no_errors / dt.n * 100)

errors_per_file_summary.pre.ln <- errors_per_file.ln %>%
  filter(!str_ends(dataset, "es6")) %>%
  group_by(dataset) %>%
  summarize(ln.no_errors = sum(ln == 0), ln.n = n(), ln.pct = ln.no_errors / ln.n * 100)

errors_per_file_summary.pre.ic <- errors_per_file.ic %>%
  filter(!str_ends(dataset, "es6")) %>%
  group_by(dataset) %>%
  summarize(ic.no_errors = sum(ic == 0), ic.n = n(), ic.pct = ic.no_errors / ic.n * 100)

files_no_errors.pre.pct <- errors_per_file_summary.pre.dt %>%
  inner_join(errors_per_file_summary.pre.ln, by="dataset") %>%
  inner_join(errors_per_file_summary.pre.ic, by="dataset") %>%
  rename_datasets() %>%
  add_row(dataset = "Overall",
          dt.no_errors = sum(.$dt.no_errors), dt.n = sum(.$dt.n),
          ln.no_errors = sum(.$ln.no_errors), ln.n = sum(.$ln.n),
          ic.no_errors = sum(.$ic.no_errors), ic.n = sum(.$ic.n),
          dt.pct = dt.no_errors / dt.n * 100,
          ln.pct = ln.no_errors / ln.n * 100,
          ic.pct = ic.no_errors / ic.n * 100)

files_no_errors_comparison <-
  inner_join(
    files_no_errors.pre.pct %>% select(dataset, ends_with("pct")),
    files_no_errors.pct %>% select(dataset, ends_with("pct")),
    by="dataset",
    suffix=c(".pre", ".es6")) %>%
  select(dataset,
         dt.pre=dt.pct.pre, dt.es6=dt.pct.es6,
         ln.pre=ln.pct.pre, ln.es6=ln.pct.es6,
         ic.pre=ic.pct.pre, ic.es6=ic.pct.es6)

files_no_errors_comparison.tex <-
  files_no_errors_comparison %>%
  mutate(dataset = ifelse(str_detect(dataset, "Overall"), "\\textbf{Overall}", dataset)) %>%
  mutate(across(where(is.double), scales::label_number(accuracy=0.1)))

save.table(files_no_errors_comparison.tex)

################################################################################
# Table: percent of correct type annotations, pre-es6 vs es6
################################################################################

accuracy_data.pre <- accuracy_data %>% filter(!str_ends(dataset, "es6"))

accuracy_summary.pre.dt <- accuracy_data.pre %>%
  filter(system == "deeptyper") %>%
  select(2:8) %>%
  filter(sigs > 0) %>%
  group_by(dataset) %>%
  summarize(dt.correct = sum(correct), dt.n = sum(n), dt.accuracy = dt.correct / dt.n * 100,
            dt.sigs = sum(sigs), dt.inferred_anys = sum(inferred_anys), dt.truth_anys = sum(truth_anys))

accuracy_summary.pre.ln <- accuracy_data.pre %>%
  filter(system == "lambdanet") %>%
  select(2:8) %>%
  filter(sigs > 0) %>%
  group_by(dataset) %>%
  summarize(ln.correct = sum(correct), ln.n = sum(n), ln.accuracy = ln.correct / ln.n * 100,
            ln.sigs = sum(sigs), ln.inferred_anys = sum(inferred_anys), ln.truth_anys = sum(truth_anys))

accuracy_summary.pre.ic <- accuracy_data.pre %>%
  filter(system == "incoder") %>%
  select(2:8) %>%
  filter(sigs > 0) %>%
  group_by(dataset) %>%
  summarize(ic.correct = sum(correct), ic.n = sum(n), ic.accuracy = ic.correct / ic.n * 100,
            ic.sigs = sum(sigs), ic.inferred_anys = sum(inferred_anys), ic.truth_anys = sum(truth_anys))

accuracy.pre.pct.full <- accuracy_summary.pre.dt %>%
  inner_join(accuracy_summary.pre.ln, by="dataset") %>%
  inner_join(accuracy_summary.pre.ic, by="dataset") %>%
  rename_datasets() %>%
  add_row(dataset = "Overall",
          dt.correct = sum(.$dt.correct), dt.n = sum(.$dt.n),
          ln.correct = sum(.$ln.correct), ln.n = sum(.$ln.n),
          ic.correct = sum(.$ic.correct), ic.n = sum(.$ic.n),
          dt.accuracy = dt.correct / dt.n * 100,
          ln.accuracy = ln.correct / ln.n * 100,
          ic.accuracy = ic.correct / ic.n * 100,
          dt.sigs = sum(.$dt.sigs), dt.inferred_anys = sum(.$dt.inferred_anys), dt.truth_anys = sum(.$dt.truth_anys),
          ln.sigs = sum(.$ln.sigs), ln.inferred_anys = sum(.$ln.inferred_anys), ln.truth_anys = sum(.$ln.truth_anys),
          ic.sigs = sum(.$ic.sigs), ic.inferred_anys = sum(.$ic.inferred_anys), ic.truth_anys = sum(.$ic.truth_anys))

accuracy.pre.pct <- accuracy.pre.pct.full %>%
  select(dataset,
         dt.correct, dt.n, dt.accuracy,
         ln.correct, ln.n, ln.accuracy,
         ic.correct, ic.n, ic.accuracy)

accuracy_comparison <-
  inner_join(
    accuracy.pre.pct %>% select(dataset, ends_with("accuracy")),
    accuracy.pct %>% select(dataset, ends_with("accuracy")),
    by="dataset",
    suffix=c(".pre", ".es6")) %>%
  select(dataset,
         dt.pre=dt.accuracy.pre, dt.es6=dt.accuracy.es6,
         ln.pre=ln.accuracy.pre, ln.es6=ln.accuracy.es6,
         ic.pre=ic.accuracy.pre, ic.es6=ic.accuracy.es6)

accuracy_comparison.tex <-
  accuracy_comparison %>%
  mutate(dataset = ifelse(str_detect(dataset, "Overall"), "\\textbf{Overall}", dataset)) %>%
  mutate(across(where(is.double), scales::label_number(accuracy=0.1)))

save.table(accuracy_comparison.tex)

################################################################################
# Graph: comparing type checking, before and after es6 transformation
################################################################################

typecheck_per_package.comparison <-
  inner_join(
    typecheck_data.pre %>%
      rename_datasets() %>%
      select(dataset, package, deeptyper=dt, lambdanet=ln, incoder=ic) %>%
      pivot_longer(cols=3:5, names_to="system", values_to="typechecks"),
    typecheck_data.es6 %>%
      rename_datasets() %>%
      select(dataset, package, deeptyper=dt, lambdanet=ln, incoder=ic) %>%
      pivot_longer(cols=3:5, names_to="system", values_to="typechecks"),
    by=c("dataset", "package", "system"),
    suffix=c(".pre", ".es6")) %>%
  drop_na(typechecks.pre, typechecks.es6) %>%
  unite(typechecks.pre, typechecks.es6, col=typechecks, sep="") %>%
  filter(typechecks != "00") %>%
  mutate(typechecks = case_when(typechecks == "00" ~ "Both fail",
                                typechecks == "11" ~ "Both typecheck",
                                typechecks == "01" ~ "Typechecks after",
                                typechecks == "10" ~ "Typechecks before")) %>%
  group_by(dataset, system, typechecks) %>%
  summarize(.groups="drop", n = n())

typechecks_es6.pdf <-
  ggplot(typecheck_per_package.comparison, aes(x=system, y=n, fill=typechecks)) +
  geom_bar(stat="identity", position=position_dodge()) +
  facet_wrap(vars(dataset), ncol=2) +
  theme(axis.title.x=element_blank()) +
  scale_x_discrete(limits=c("deeptyper","lambdanet","incoder"),
                   labels=c("deeptyper"="DeepTyper","lambdanet"="LambdaNet","incoder"="InCoder")) +
  scale_y_continuous(name="Packages") +
  scale_fill_brewer(palette=brewer3, direction=-1)

save.graph(typechecks_es6.pdf)
